version: 2.1
orbs:
  node: circleci/node@5

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - run: echo "test"

workflows:
  version: 2
  build-and-publish:
    jobs:
      - test:
          filters:
            branches:
              only: main
            tags:
              only: /^v.*/
      - publish-npm:
          requires:
            - test
          filters:
            branches:
              only: main
            tags:
              only: /^v.*/
