version: 2.1
orbs:
  node: circleci/node@5

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install bun
          command: |
            curl -fsSL https://bun.sh/install | bash
            echo 'export BUN_INSTALL="$HOME/.bun"' >> $BASH_ENV
            echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Build package
          command: cd packages/react-drager && bun install && bun run build
      - persist_to_workspace:
          root: .
          paths:
            - packages/react-drager/dist
            - packages/react-drager/package.json
            - packages/react-drager/README.md
            - packages/react-drager/LICENSE

  publish-npm:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Debug Workspace
          command: |
            cd packages/react-drager
            echo "当前目录内容："
            ls -la
            echo "package.json内容："
            cat package.json
      - run:
          name: Update version from git tag
          command: |
            VERSION=${CIRCLE_TAG#v}
            echo "设置版本: ${VERSION}"
            cd packages/react-drager
            npm version $VERSION --no-git-tag-version --allow-same-version
      - run:
          name: Authenticate with NPM
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
            echo "验证NPM登录："
            npm whoami || echo "NPM认证失败"
      - run:
          name: Publish to NPM
          command: |
            cd packages/react-drager
            echo "准备发布的文件："
            npm pack --dry-run
            echo "开始发布..."
            npm publish --access public --verbose || echo "发布失败，错误码：$?"

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-npm:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
